# Generated by Django 2.1 on 2018-08-26 18:35

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180819_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='正文'),
        ),
    ]
